const recommend = [
    {
        "idMeal":"53058","strMeal":"Croatian Bean Stew","strDrinkAlternate":null,"strCategory":"Beef","strArea":"Croatian","strInstructions":"Heat the oil in a pan. Add the chopped vegetables and saut\u00e9 until tender. Take a pot, empty the beans together with the vegetables into it, put the sausages inside and cook for further 20 minutes on a low heat. Or, put it in an oven and bake it at a temperature of 180\u00baC\/350\u00baF for 30 minutes. This dish is even better reheated the next day.","strMealThumb":"https:\/\/www.themealdb.com\/images\/media\/meals\/tnwy8m1628770384.jpg","strTags":"Warming, Soup, Beans","strYoutube":"https:\/\/www.youtube.com\/watch?v=mrjnQal3S1A","strIngredient1":"Cannellini Beans","strIngredient2":"Vegetable Oil","strIngredient3":"Tomatoes","strIngredient4":"Challots","strIngredient5":"Garlic","strIngredient6":"Parsley","strIngredient7":"Chorizo","strIngredient8":"","strIngredient9":"","strIngredient10":"","strIngredient11":"","strIngredient12":"","strIngredient13":"","strIngredient14":"","strIngredient15":"","strIngredient16":"","strIngredient17":"","strIngredient18":"","strIngredient19":"","strIngredient20":"","strMeasure1":"2 cans","strMeasure2":"3 tbs","strMeasure3":"2 cups ","strMeasure4":"5","strMeasure5":"2 cloves","strMeasure6":"Pinch","strMeasure7":"1\/2 kg chopped ","strMeasure8":" ","strMeasure9":" ","strMeasure10":" ","strMeasure11":" ","strMeasure12":" ","strMeasure13":" ","strMeasure14":" ","strMeasure15":" ","strMeasure16":" ","strMeasure17":" ","strMeasure18":" ","strMeasure19":" ","strMeasure20":" ","strSource":"https:\/\/www.visit-croatia.co.uk\/croatian-cuisine\/croatian-recipes\/","strImageSource":null,"strCreativeCommonsConfirmed":null,"dateModified":null
    },
    {
        "idMeal":"52929","strMeal":"Timbits","strDrinkAlternate":null,"strCategory":"Dessert","strArea":"Canadian","strInstructions":"Sift together dry ingredients.\r\nMix together wet ingredients and incorporate into dry. Stir until smooth.\r\nDrop by teaspoonfuls(no bigger) into hot oil (365 degrees, no hotter), turning after a few moments until golden brown on all sides.\r\nRemove and drain.\r\nRoll in cinnamon sugar while still warm and serve.","strMealThumb":"https:\/\/www.themealdb.com\/images\/media\/meals\/txsupu1511815755.jpg","strTags":"Snack,Treat","strYoutube":"https:\/\/www.youtube.com\/watch?v=fFLn1h80AGQ","strIngredient1":"Flour","strIngredient2":"Sugar","strIngredient3":"Baking Powder","strIngredient4":"Salt","strIngredient5":"Egg","strIngredient6":"Milk","strIngredient7":"Oil","strIngredient8":"Oil","strIngredient9":"Icing Sugar","strIngredient10":"","strIngredient11":"","strIngredient12":"","strIngredient13":"","strIngredient14":"","strIngredient15":"","strIngredient16":"","strIngredient17":"","strIngredient18":"","strIngredient19":"","strIngredient20":"","strMeasure1":"2 cups ","strMeasure2":"1\/3 cup","strMeasure3":"3 tsp","strMeasure4":"\u00bd tsp","strMeasure5":"1 beaten","strMeasure6":"\u00be cup","strMeasure7":"3 tbs","strMeasure8":"for frying","strMeasure9":"garnish","strMeasure10":"","strMeasure11":"","strMeasure12":"","strMeasure13":"","strMeasure14":"","strMeasure15":"","strMeasure16":"","strMeasure17":"","strMeasure18":"","strMeasure19":"","strMeasure20":"","strSource":"http:\/\/www.geniuskitchen.com\/recipe\/drop-doughnuts-133877","strImageSource":null,"strCreativeCommonsConfirmed":null,"dateModified":null
    },
    {
        "idMeal":"52976","strMeal":"Cashew Ghoriba Biscuits","strDrinkAlternate":null,"strCategory":"Dessert","strArea":"Tunisian","strInstructions":"Preheat the oven at 180 C \/ Gas 4. Line a baking tray with greaseproof paper.\r\nIn a bowl, mix the cashews and icing sugar. Add the egg yolks and orange blossom water and mix to a smooth homogeneous paste.\r\nTake lumps of the cashew paste and shape into small balls. Roll the balls in icing sugar and transfer to the baking tray. Push an almond in the centre of each ghribia.\r\nBake until the biscuits are lightly golden, about 20 minutes. Keep an eye on them, they burn quickly.","strMealThumb":"https:\/\/www.themealdb.com\/images\/media\/meals\/t3r3ka1560461972.jpg","strTags":null,"strYoutube":"https:\/\/www.youtube.com\/watch?v=IqXEZUk4hWI","strIngredient1":"Cashew Nuts","strIngredient2":"Icing Sugar","strIngredient3":"Egg Yolks","strIngredient4":"Orange Blossom Water","strIngredient5":"Icing Sugar","strIngredient6":"Almonds","strIngredient7":"","strIngredient8":"","strIngredient9":"","strIngredient10":"","strIngredient11":"","strIngredient12":"","strIngredient13":"","strIngredient14":"","strIngredient15":"","strIngredient16":"","strIngredient17":"","strIngredient18":"","strIngredient19":"","strIngredient20":"","strMeasure1":"250g","strMeasure2":"100g ","strMeasure3":"2","strMeasure4":"2 tbs","strMeasure5":"To Glaze","strMeasure6":"100g ","strMeasure7":" ","strMeasure8":" ","strMeasure9":" ","strMeasure10":" ","strMeasure11":" ","strMeasure12":" ","strMeasure13":" ","strMeasure14":" ","strMeasure15":" ","strMeasure16":" ","strMeasure17":" ","strMeasure18":" ","strMeasure19":" ","strMeasure20":" ","strSource":"http:\/\/allrecipes.co.uk\/recipe\/40152\/cashew-ghoriba-biscuits.aspx","strImageSource":null,"strCreativeCommonsConfirmed":null,"dateModified":null
    }
];

export default recommend;